### PR TITLE
Add Data DOI and Data Publisher

### PR DESCRIPTION
**Pull request by sbesson**
Changes have been applied to `prod64`

### CODE REVIEW

**Comment by dominikl** [comment]
👍

**Review by francesw — CHANGES_REQUESTED** [review]
In keeping with format for other studies, Study Data DOI should have "10.17867/10000119" before URL.

**Comment by sbesson** [comment]
The `Data DOI` in the IDR studies is generated from the DOI parsed from the study file (which should be always as `http[s]://[dx.]doi.org/<doi_suffix>`. I don't think any study file currently stores that information using the IDR display format.

**Comment by sbesson** [comment]
Merging after discussion with @francesw

**Pull request merged**
